Repository boostcampwm-2022/web23_MoMyeon, pull requests merged in 2022-11, with the labels that each got.

#8 Feat/#3 : 메인페이지, 헤더, 로그인 모달
  frontend/components/header/dropDown.tsx
  frontend/components/header/header.component.tsx
  frontend/components/header/header.d.ts
  frontend/components/mainPost/postCard.component.tsx
  frontend/components/mainPost/postContainer.component.tsx
  frontend/components/modal/loginModal.component.tsx
  frontend/components/modal/loginModal.d.ts
  frontend/constants/apiKeys.ts
  frontend/head/home.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/posts.ts
  frontend/pages/index.tsx
  frontend/public/icon/dropDown.png
  frontend/public/icon/github.png
  frontend/public/icon/loginUser.png
  frontend/public/icon/logo.png
  frontend/public/icon/modalExit.png
  frontend/public/icon/user.png
  frontend/styles/Header.module.scss
  frontend/styles/Home.module.scss
  frontend/styles/LoginModal.module.scss
  frontend/styles/PostCard.module.scss
  frontend/styles/_color.scss
  frontend/styles/_common.scss
  frontend/styles/globals.css
  frontend/tsconfig.json
  frontend/types/auth.ts
  frontend/types/common.ts
  frontend/types/posts.ts
  frontend/utils/api/getPosts.ts
Labels: 프론트엔드

#9 Feat/#2 모의 면접 모집 UI
  frontend/components/createPostForm.component.tsx
  frontend/components/mockHeader.component.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/post/create.tsx
  frontend/public/favicon.ico
  frontend/public/fonts/lineSeedSansKR/LINESeedSansKR-Bd.woff2
  frontend/public/fonts/lineSeedSansKR/LINESeedSansKR-Rg.woff2
  frontend/public/fonts/lineSeedSansKR/LINESeedSansKR-Th.woff2
  frontend/styles/Create.module.css
  frontend/styles/globals.css
  frontend/yarn.lock
Labels: 프론트엔드

#17 ERD에 따라 Typeorm 엔티티 생성, 관계 설정
  backend/.gitignore
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/entities/category.entity.ts
  backend/src/entities/feedback.entity.ts
  backend/src/entities/interview.entity.ts
  backend/src/entities/interviewCategory.entity.ts
  backend/src/entities/interviewQuestion.entity.ts
  backend/src/entities/item.entity.ts
  backend/src/entities/resume.entity.ts
  backend/src/entities/simpleQuestion.entity.ts
  backend/src/entities/user.entity.ts
  backend/src/entities/userInterview.entity.ts
  backend/src/entities/userQuestion.entity.ts
  backend/src/enum/questionType.enum.ts
  backend/src/enum/userInterviewStatus.enum.ts
  backend/src/main.ts
  backend/src/test/test.controller.ts
  backend/src/test/test.module.ts
  backend/src/test/test.service.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/yarn.lock
Labels: 백엔드

#26 feat: 백엔드서버, DB 도커라이징 #25
  backend/.dockerignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/init.sql
Labels: 백엔드

#24 Feat/category/#18
  backend/src/app.module.ts
  backend/src/category/category.controller.ts
  backend/src/category/category.module.ts
  backend/src/category/category.service.ts
  backend/src/category/dto/create-category.dto.ts
  backend/src/category/dto/update-category.dto.ts
  backend/src/main.ts
Labels: 백엔드

#35 깃허브 로그인 구현 #28
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/github-login.dto.ts
  backend/src/guards/jwtAuth.guard.ts
  backend/src/interfaces/user.interface.ts
  backend/src/middlewares/appLoger.middleware.ts
  backend/src/test/test.controller.ts
  backend/src/test/test.module.ts
  backend/src/test/test.service.ts
  backend/src/user/dto/github-login.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.decorator.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/yarn.lock
Labels: 백엔드

#45 refactor: prettier 적용 부분이라 PR 분리 했습니다.
  frontend/.prettierignore
  frontend/components/modal/loginModal.component.tsx
  frontend/head/postPage.tsx
  frontend/mockData/categoryData.ts
  frontend/mockData/postPageData.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/v1/category.ts
  frontend/pages/api/v1/interview.ts
  frontend/pages/index.tsx
  frontend/pages/post/[id].tsx
  frontend/pages/post/create.tsx
  frontend/styles/Create.module.scss
  frontend/styles/PostCard.module.scss
  frontend/styles/PostPage.module.scss
  frontend/styles/globals.css
  frontend/types/category.ts
  frontend/types/headMetaData.ts
  frontend/types/posts.ts
  frontend/utils/convertEpochStringToLocale.ts
  frontend/utils/dateFormmat.ts
  frontend/yarn.lock
Labels: 프론트엔드

#44 Feat/interview/#23
  backend/src/app.module.ts
  backend/src/entities/interview.entity.ts
  backend/src/interview/dto/create-interview.dto.ts
  backend/src/interview/dto/select-interview.dto.ts
  backend/src/interview/dto/update-interview.dto.ts
  backend/src/interview/interview.controller.ts
  backend/src/interview/interview.module.ts
  backend/src/interview/interview.service.ts
Labels: backend

#46 feat: 로그아웃 구현, refactor: useHook, 컴포넌트 분리
  frontend/components/button/interviewJoinButton.tsx
  frontend/components/categoryTag/CategoryTag.component.tsx
  frontend/components/createPostForm/createPostForm.component.tsx
  frontend/components/header/dropDown.tsx
  frontend/components/header/header.component.tsx
  frontend/components/modal/loginModal.d.ts
  frontend/constants/apiKeys.ts
  frontend/mockData/postData.ts
  frontend/pages/api/github.ts
  frontend/pages/api/logout.ts
  frontend/pages/post/[id].tsx
  frontend/pages/post/create.tsx
  frontend/styles/PostPage.module.scss
  frontend/styles/_color.scss
  frontend/utils/api/getData.ts
  frontend/utils/api/logout.ts
  frontend/utils/hooks/useCategoryQuery.ts
Labels: 프론트엔드

#54 Feat/postCRUD 깃허브 로그인 방식 변경, 유저정보 확인 변경, 프론트 API 연결
  frontend/components/categoryTag/CategoryTag.component.tsx
  frontend/components/categoryTag/CategoryTagItem.component.tsx
  frontend/components/createPostForm/createPostForm.component.tsx
  frontend/components/createPostForm/createPostForm.d.ts
  frontend/components/header/header.component.tsx
  frontend/constants/apiKeys.ts
  frontend/mockData/postPageData.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/api/github.ts
  frontend/pages/api/logout.ts
  frontend/pages/index.tsx
  frontend/pages/post/[id].tsx
  frontend/pages/post/create.tsx
  frontend/styles/PostPage.module.scss
  frontend/types/auth.ts
  frontend/types/posts.ts
  frontend/utils/api/createPost.ts
  frontend/utils/api/getPostById.ts
  frontend/utils/hooks/useCategoryQuery.ts
  frontend/utils/hooks/useGithubLoginMutation.ts
  frontend/utils/hooks/useUserDataQuery.ts
  frontend/yarn.lock
Labels: 리뷰요청, 프론트엔드

#57 Feat/question/#50 랜덤 질문을 출력/#55 나의 질문 추가/조회/삭제
  backend/src/app.module.ts
  backend/src/enum/questionType.enum.ts
  backend/src/enum/userInterviewStatus.enum.ts
  backend/src/guards/jwtAuth.guard.ts
  backend/src/interfaces/user.interface.ts
  backend/src/question/dto/create-question.dto.ts
  backend/src/question/dto/create-user-question.dto.ts
  backend/src/question/dto/update-question.dto.ts
  backend/src/question/dto/update-user-question.dto.ts
  backend/src/question/question.controller.ts
  backend/src/question/question.module.ts
  backend/src/question/question.service.ts
Labels: backend

#58 모의면접 참가자 정보 조회 api 구현
  backend/src/guards/jwtAuth.guard.ts
  backend/src/interview/interview.controller.ts
  backend/src/interview/interview.module.ts
  backend/src/interview/interview.service.ts
  backend/src/middlewares/appLoger.middleware.ts
Labels: 백엔드
