Repository boostcampwm-2022/web23_MoMyeon, pull requests merged in 2022-12, with the labels that each got.

#70 Feat/interview api/#48 interview 리스트, 상세 관련 수정
  backend/src/category/category.service.ts
  backend/src/interview/interview.controller.ts
  backend/src/interview/interview.module.ts
  backend/src/interview/interview.service.ts
  frontend/components/mainFilter/categoryContainer.component.tsx
  frontend/pages/index.tsx
  frontend/types/category.ts
Labels: 백엔드

#78 docker-compose 환경변수 수정, redis 설정
  backend/docker-compose.yml
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/redis.conf
  backend/src/feedback/feedback.controller.ts
  backend/src/feedback/feedback.module.ts
  backend/src/feedback/feedback.service.ts
  backend/yarn.lock
Labels: 백엔드

#77 Feat/mediasoup/#69 ) <Pull 받으면 yarn install 꼭 !> mediasoup 적용, 개발용 분리
  .github/workflows/main.yml
  frontend/.gitignore
  frontend/package.json
  frontend/pages/room/[room].tsx
  frontend/pages/subroom/[id].tsx
  frontend/styles/Webrtc.module.scss
  frontend/styles/video.module.scss
  frontend/yarn.lock
  mediaServer/.gitignore
  mediaServer/localTestServer.js
  mediaServer/package-lock.json
  mediaServer/package.json
  mediaServer/server.js
  mediaServer/subroom/localTestServer.js
  mediaServer/subroom/server.js
  mediaServer/yarn.lock
Labels: 리뷰요청

#91 Feat 로그아웃
  backend/src/auth/auth.controller.ts
  backend/src/interview/interview.service.ts
  frontend/components/header/dropDown.tsx
  frontend/constants/apiKeys.ts
  frontend/pages/api/logout.ts
  frontend/utils/api/logout.ts
  frontend/yarn.lock
Labels: 프론트엔드, 백엔드

#96 Fix: 사용자 인증이 필요한 api 요청엔 credential을 보내야 함
  frontend/pages/_app.tsx
Labels: 프론트엔드

#106 피드백 저장, 조회 api 구현
  backend/src/config/redis.conf
  backend/src/entities/feedback.entity.ts
  backend/src/feedback/dto/save-feedback.dto.ts
  backend/src/feedback/feedback.controller.ts
  backend/src/feedback/feedback.module.ts
  backend/src/feedback/feedback.service.ts
  backend/src/interfaces/feedback.interface.ts
Labels: 백엔드

#110 feat: my page resume api
  backend/src/user/dto/create-resume.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
Labels: 백엔드

#109 Feat/program/#82 면접 프로그램 적용 파트 2
  frontend/components/button/audioToggleButton.component.tsx
  frontend/components/button/interviewJoinButton.component.tsx
  frontend/components/button/toolBoxButton.component.tsx
  frontend/components/button/videoToggleButton.component.tsx
  frontend/components/header/header.component.tsx
  frontend/components/mediasoupVideo/mediasoupVideo.component.tsx
  frontend/pages/post/[id].tsx
  frontend/pages/room/[room].tsx
  frontend/styles/Question.module.scss
  frontend/styles/room.module.scss
Labels: 프론트엔드, 미디어서버

#120 feat: 나갈 때 정상적으로 나갈 수 있게, 버튼 UI, 컴포넌트 수정
  frontend/components/button/audioToggleButton.component.tsx
  frontend/components/button/muteButton.component.tsx
  frontend/components/button/toolBoxButton.component.tsx
  frontend/components/button/videoToggleButton.component.tsx
  frontend/components/mainPost/postCard.component.tsx
  frontend/components/mediasoupVideo/mediasoupVideo.component.tsx
  frontend/pages/room/[room].tsx
  frontend/styles/room.module.scss
Labels: 프론트엔드

#121 Fix/mypage resume/#116 빌드 오류 수정, 폰트 글로벌로
  frontend/pages/question/[id].tsx
  frontend/styles/globals.css
Labels: 프론트엔드

#128 fix: (get) interview/:id member 형 변환#126
  backend/src/interview/interview.service.ts
Labels: 백엔드

#130 refresh 토큰 로직 구현
  backend/src/auth/auth.service.ts
  backend/src/guards/jwtAuth.guard.ts
Labels: 백엔드

#131 feat: 화상프로그램 질문 조회
  backend/src/question/question.controller.ts
  backend/src/question/question.service.ts
Labels: 백엔드

#174 redis에서 질문 저장 / 가져오기
  backend/src/question/question.controller.ts
  backend/src/question/question.module.ts
  backend/src/question/question.service.ts
Labels: 백엔드

#186 모의면접 신청 시 마감여부 확인 로직 추가
  backend/src/entities/interview.entity.ts
  backend/src/enum/userInterviewStatus.enum.ts
  backend/src/feedback/feedback.service.ts
  backend/src/guards/interview.guard.ts
  backend/src/interview/interview.controller.ts
  backend/src/interview/interview.service.ts
  backend/src/question/question.controller.ts
  backend/src/question/question.service.ts
Labels: 백엔드

#185 feat: 인터뷰 정보 조회 isStart 추가
  backend/src/interview/interview.service.ts
Labels: 백엔드

#183 feat: 종합질문 생성 로직 수정#179
  backend/src/question/question.service.ts
Labels: 백엔드

#189 Feat/interview question/#179
  backend/src/question/question.service.ts
Labels: 백엔드

#195 종합 피드백 조회 요청 시 면접 멤버가 아닌경우 에러처리
  backend/src/feedback/feedback.controller.ts
  backend/src/feedback/feedback.module.ts
  backend/src/feedback/feedback.service.ts
  backend/src/guards/member.guard.ts
Labels: 백엔드

#199 Feat/feedback/#181 피드백 컴포넌트, 피드백 동시 진행
  frontend/components/feedback/feedback.component.tsx
  frontend/components/feedback/feedbackFilterHeader.component.tsx
  frontend/components/feedback/feedbackItem.component.tsx
  frontend/components/header/header.component.tsx
  frontend/components/mediasoupVideo/mediasoupVideo.component.tsx
  frontend/components/modal/loginModal.component.tsx
  frontend/components/question/answer.component.tsx
  frontend/constants/apiKeys.ts
  frontend/pages/room/[room].tsx
  frontend/states/feedbackStarted.ts
  frontend/states/loginModal.ts
  frontend/styles/feedback.module.scss
  frontend/styles/room.module.scss
  frontend/types/feedback.ts
  frontend/utils/api/getFeedbacks.ts
  frontend/utils/hooks/useFeeedbackQuery.ts
  frontend/utils/hooks/useUserDataQuery.ts
  mediaServer/localTestServer.js
  mediaServer/server.js
Labels: 프론트엔드, 미디어서버

#205 hotfix: 면접 상태가 feedback에서 다시 end로 변경되는 경우 수정
  backend/src/question/question.service.ts
Labels: 백엔드

#216 Fix/find query/#214
  backend/src/interview/interview.service.ts
  frontend/components/mainPost/postCard.component.tsx
  frontend/types/posts.ts
Labels: 프론트엔드, 백엔드

#220 Fix/css 디테일/#219
  frontend/styles/MypageInterview.module.scss
  frontend/styles/MypageQuestion.module.scss
  frontend/styles/MypageResume.module.scss
  frontend/styles/OpenRoom.module.scss
  frontend/styles/PostCard.module.scss
  frontend/styles/PostCardMypage.module.scss
  frontend/styles/PostPage.module.scss
  frontend/styles/Room.module.scss
Labels: 프론트엔드, 백엔드
